services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data-media:/var/opt/mssql/data

volumes:
  sql-data-media: